<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            ['nombre' => 'CAMARÓN', 'categoria_id' => 2],
            ['nombre' => 'HAMBURGUESAS', 'categoria_id' => 2],
            ['nombre' => 'HAMB.ARRACHERA', 'categoria_id' => 2],
            ['nombre' => 'MARINADOR', 'categoria_id' => 2],
            ['nombre' => 'PAVO', 'categoria_id' => 2],
            ['nombre' => 'PAN SAZON', 'categoria_id' => 2],
            ['nombre' => 'PAPA GAJO', 'categoria_id' => 2],
            ['nombre' => 'PAN WAFFLE', 'categoria_id' => 2],
            ['nombre' => 'PAPA CANOA', 'categoria_id' => 2],
            ['nombre' => 'PAPA IDAHO', 'categoria_id' => 2],
            ['nombre' => 'PAN MOLIDO', 'categoria_id' => 2],
            ['nombre' => 'PAPA WAFLE', 'categoria_id' => 2],
            ['nombre' => 'PAPA CARITA', 'categoria_id' => 2],
            ['nombre' => 'PAPA CÁSCARA', 'categoria_id' => 2],
            ['nombre' => 'PAPA ESPIRAL', 'categoria_id' => 2],
            ['nombre' => 'PAPA CATERPAC', 'categoria_id' => 2],
            ['nombre' => 'PAPA EMOTICON', 'categoria_id' => 2],
            ['nombre' => 'PAPA ECONÓMICA', 'categoria_id' => 2],
            ['nombre' => 'PAPA A LA FRANCESA', 'categoria_id' => 2],
            ['nombre' => 'PALOMITA DE PECHIGA', 'categoria_id' => 2],
            ['nombre' => 'SALMÓN (PZ)', 'categoria_id' => 2],
            ['nombre' => 'MC NUGGET', 'categoria_id' => 2],
            ['nombre' => 'DEDOS DE QUESO', 'categoria_id' => 2],
            ['nombre' => 'TENDER', 'categoria_id' => 2],
            ['nombre' => 'DINO Y NACHO', 'categoria_id' => 2],
            ['nombre' => 'PIERNA AHUMADA', 'categoria_id' => 2],
            ['nombre' => 'PIERNA DE PAVO AHUMADA', 'categoria_id' => 2],
            ['nombre' => 'SIRLONE', 'categoria_id' => 2],
            ['nombre' => 'TILAPIA', 'categoria_id' => 2],
            ['nombre' => 'TIRAS GRILL', 'categoria_id' => 2],
            ['nombre' => 'TIRA DE ANTOJO', 'categoria_id' => 2],
            ['nombre' => 'ALA MARINADA', 'categoria_id' => 2],
            ['nombre' => 'ALITA PICOSITA', 'categoria_id' => 2],
            ['nombre' => 'ALA GRILL(AHUMADA)', 'categoria_id' => 2],
            ['nombre' => 'GLOBAL', 'categoria_id' => 2],
            ['nombre' => 'BONNELESS', 'categoria_id' => 2],
            ['nombre' => 'BOLITAS DE QUESO', 'categoria_id' => 2],
            ['nombre' => 'LOGANIZA', 'categoria_id' => 2],
            ['nombre' => 'MOLE', 'categoria_id' => 2],
            ['nombre' => 'POLLO NAVIDEÑO', 'categoria_id' => 2],
            ['nombre' => 'AROS', 'categoria_id' => 2],
            ['nombre' => 'ARTISANO', 'categoria_id' => 2],
            ['nombre' => 'ARRACHERA (PZ/BISTEC)', 'categoria_id' => 2],
            ['nombre' => 'BRACITOS', 'categoria_id' => 2],
            ['nombre' => 'ATÚN', 'categoria_id' => 2],
            ['nombre' => 'HUEVO JJ', 'categoria_id' => 2],
            ['nombre' => 'HUEVO ROJO', 'categoria_id' => 2],
            ['nombre' => 'HUEVO BCO JJ', 'categoria_id' => 2],
            ['nombre' => 'HUEVO BLANCO', 'categoria_id' => 2],
            ['nombre' => 'MUSLO MARINAD', 'categoria_id' => 2],
            ['nombre' => 'NUGGETS', 'categoria_id' => 2],
            ['nombre' => 'NUGGET ESTRELLA', 'categoria_id' => 2],
            ['nombre' => 'NUGGET MANTEQUILLA', 'categoria_id' => 2],
            ['nombre' => 'PULPO', 'categoria_id' => 2],
            ['nombre' => 'P/M TOTE', 'categoria_id' => 1],
            ['nombre' => '(24)', 'categoria_id' => 1],
            ['nombre' => '(25)', 'categoria_id' => 1],
            ['nombre' => '(5895)', 'categoria_id' => 1],
            ['nombre' => 'CABEZA', 'categoria_id' => 1],
            ['nombre' => 'GALLINA', 'categoria_id' => 1],
            ['nombre' => 'MARINADOR', 'categoria_id' => 1],
            ['nombre' => 'PATA', 'categoria_id' => 1],
            ['nombre' => 'PAVO', 'categoria_id' => 1],
            ['nombre' => 'PATA ESCALDADA', 'categoria_id' => 1],
            ['nombre' => 'DESPERDICIO', 'categoria_id' => 1],
            ['nombre' => 'PEDIDO', 'categoria_id' => 1],
            ['nombre' => 'PECHUGA', 'categoria_id' => 1],
            ['nombre' => 'PECHUGA CHICA', 'categoria_id' => 1],
            ['nombre' => 'PECHUGA, GOLPE', 'categoria_id' => 1],
            ['nombre' => 'PECHUGA DE TOTE', 'categoria_id' => 1],
            ['nombre' => 'PECHUGA CONGELADA', 'categoria_id' => 1],
            ['nombre' => 'RETAZO', 'categoria_id' => 1],
            ['nombre' => 'HIGADO', 'categoria_id' => 1],
            ['nombre' => 'HIGADO AVI', 'categoria_id' => 1],
            ['nombre' => 'PIERNA SOLA', 'categoria_id' => 1],
            ['nombre' => 'PIERNA / MUSLO', 'categoria_id' => 1],
            ['nombre' => 'PIERNA MARINADA', 'categoria_id' => 1],
            ['nombre' => 'ALA NATURAL', 'categoria_id' => 1],
            ['nombre' => 'ALA MARINADA', 'categoria_id' => 1],
            ['nombre' => 'PM GOLPE', 'categoria_id' => 1],
            ['nombre' => 'LONGANIZA', 'categoria_id' => 1],
            ['nombre' => 'MOLLEJA', 'categoria_id' => 1],
            ['nombre' => 'MOLLEJA BLANCA', 'categoria_id' => 1],
            ['nombre' => 'POLLO ENTERO', 'categoria_id' => 1],
            ['nombre' => 'POLLO NAVIDEÑO', 'categoria_id' => 1],
            ['nombre' => 'POLLO ROJO O GOLPEADO', 'categoria_id' => 1],
            ['nombre' => 'ROJO', 'categoria_id' => 1],
            ['nombre' => 'HR', 'categoria_id' => 1],
            ['nombre' => 'HUEVO', 'categoria_id' => 1],
            ['nombre' => 'HUEVO ROJO', 'categoria_id' => 1],
            ['nombre' => 'HUEVO ROTO', 'categoria_id' => 1],
            ['nombre' => 'HUEVO CHAROLA', 'categoria_id' => 1],
            ['nombre' => 'MUSLO', 'categoria_id' => 1],
            ['nombre' => 'MUSLO 2', 'categoria_id' => 1],
            ['nombre' => 'PULPA PARA MOLER', 'categoria_id' => 1],
            ['nombre' => 'AVI ROSTI', 'categoria_id' => 1],
        ])->each(fn($producto) => Producto::create($producto));
    }
}
